[mysql.localhost]
host = "127.0.0.1"
port = 3306
defaults_file = "/etc/mysql/backup.cnf"

[backup]
dir = "/srv/backup"

[backup.mysql.localhost]
encrypt = { enabled = true, key-file = "", threads = 8 }
databases = []
databases-exclude = []
incremental = true
incremental-basedir = ""
parallel_threads = 8
rsync = false
