[backup]
basedir = ""

[mysql-r1]
type = "MySQL"
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"

[mysql-r1.backup]
type = "mysqldump"
databases = ["auth"]
interval = "*/30 * * * * *"
keep_last = 7
