[backup]
basedir = ""

[mysql-r1]
type = "MySQL"
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"

[mysql-r1.backup]
type = "mysqldump"
parallel_threads = 16
databases = ["auth", "wordpress"]
interval = "* * * * * *"
keep_last = 7

[mysql-r1.backup.encrypt]
key_file = "/etc/mysql/backup.key"
threads = 16

[mysql-r1.backup.incremental]
enabled = true
basedir = "/home"
